spring:
  datasource:
    url: jdbc:postgresql://localhost:5333/drugstore
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  logging:
      level:
        org.hibernate: ERROR

  jpa:
    show-sql: true